services:
  icecast:
    image: moul/icecast
    container_name: icecast
    restart: unless-stopped
    volumes:
      - ./icecast-config/icecast.xml:/etc/icecast2/icecast.xml:ro

  broadcaster:
    build: ./broadcaster
    container_name: broadcaster
    restart: unless-stopped
    environment:
      - ICECAST_HOST=icecast
      - ICECAST_PORT=8000
      - ICECAST_PASSWORD=EtherIsBetter
      - WS_PORT=8081
    depends_on:
      - icecast

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - icecast
      - broadcaster

volumes:
  caddy_data:
  caddy_config:
